config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :edit, :create, :update]
  resources :cat_rental_requests, only: [:new, :create] do
    member do 
      post 'approve'
      post 'deny'
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  description :text             not null
#  sex         :string(1)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'

class Cat < ApplicationRecord 

include ActionView::Helpers::DateHelper

  CAT_COLORS = %w(gray white ginger brown cream)
  validates :color, inclusion: { in: CAT_COLORS }
  validates :sex, inclusion: { in: %w(M F) } 
  validates :birth_date, :name, :description, presence: true 
  
 has_many :rental_requests, 
  class_name: :CatRentalRequest,
  dependent: :destroy

  def age 
    time_ago_in_words(birth_date)
  end 
 
end 

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#

class CatRentalRequest < ApplicationRecord 
  validates :status, inclusion: { in: %w(APPROVED DENIED PENDING) } 
  validates :cat_id, :start_date, :end_date, presence: true 
  validate :does_not_overlap_approved_request

  belongs_to :cat

  def overlapping_requests
    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: self.cat_id)
      .where.not('start_date > :end_date OR end_date < :start_date', 
      start_date: start_date, end_date: end_date)
  end 

  def overlapping_approved_request
    overlapping_requests.where('status = \'APPROVED\'') 
  end 

  def overlapping_pending_request
    overlapping_requests.where('status = \'PENDING\'') 
  end 

  def does_not_overlap_approved_request
    
    return if self.denied? 

    if overlapping_approved_request.exists? 
      errors[:base] << "Request conflicts with existing approved request"
    end
  end 

  def approved!
   self.transaction do 
    self.status = 'APPROVED'
    self.save!

    overlapping_pending_request.update_all(status: "DENIED")
   end 
  end 

  def deny! 
    self.status = 'DENIED'
    self.save!
  end 

  def pending? 
    self.status == "PENDING"
  end 

  def denied?
    self.status == "DENIED"
  end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController 
 
  def new 
    @cat_rental = CatRentalRequest.new
    @cats = Cat.all 
    render :new
  end

  def create 
    @cat_rental = CatRentalRequest.new(cat_rental_params)

    if @cat_rental.save
      redirect_to cat_url(@cat_rental.cat_id) 
    else 
      render :new
    end 
  end 

  def approve 
    current_cat_rental_request.approved!
    redirect_to cat_url(current_cat) 
  end 

  def deny 
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat) 
  end 

  private 
  def current_cat_rental_request
    @rental_request ||= 
      CatRentalRequest.includes(:cat).find(params[:id])
  end 

  def current_cat
    current_cat_rental_request.cat
  end 

  def cat_rental_params 
   params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end 
end 

app/controllers/cats_controller.rb
class CatsController < ApplicationController 
  def index 
    @cats = Cat.all 

    render :index
  end 

  def show 
    @cat = Cat.find_by(id: params[:id])

    if @cat
      render :show
    else
      redirect_to '/cats'
    end
    
  end 
  
  def new 
    @cat = Cat.new 
    render :new
  end

  def create 
    @cat = Cat.new(cat_params)
   
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end 

  def edit 
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end 

  def update 
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else 
      render :edit
    end 
  end 


  def cat_params 
    params.require(:cat).permit(:birth_date, :color, :name, :description, :sex)
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Rent a cat!</h1>

<form action = "/cat_rental_requests" method ="POST" > 
  Pick a Cat to Rent:
   <select name="cat_rental_request[cat_id]">
    <%Cat.all.each do |cat| %>
      <option 
      value="<%=cat.id%>" > <%=cat.name%> </option>
    <%end%>
    </select>
  <br>

  <label for="start_date">Start Date</label>
    <input 
    id="start_date" 
    type="date" 
    name="cat_rental_request[start_date]" 
    value="">
  <br>

  <label for="end_date">End Date</label>
    <input 
    id="end_date" 
    type="date" 
    name="cat_rental_request[end_date]" 
    value="">

  <br>  
  <input type="submit" value="Submit Rental!">
</form>

<a href="<%= cats_url %>">Home</a>

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url%>

<form action="<%=action_url%>" method="POST">
<%if action == :edit %>
  <input 
    type="hidden" 
    name="_method" 
    value="PATCH">
<%end%> 

  <label for="name">Name</label>
  <input  
    id="name" 
    type="text" 
    name="cat[name]" 
    value="<%=@cat.name%>"> 

  <br>
  <label for="birth_date">Birth Date</label>
  <input 
    id="birth_date" 
    type="date" 
    name="cat[birth_date]" 
    value="<%=@cat.birth_date%>">

  <br>
    <select name="cat[color]">
    <%Cat::CAT_COLORS.each do |color| %>
      <option 
      value="<%=color%>" <%= "selected" if @cat.color == color%>> <%=color%></option>
    <%end%>
    </select>
  <br>

  <input 
    type="radio" 
    name="cat[sex]" 
    value ="M" <%="checked" if @cat.sex == 'M'%> >Male<br>
  <input 
    type="radio" 
    name="cat[sex]" 
    value ="F" <%="checked" if @cat.sex == 'F'%>>Female<br>

  <label for="description">Description</label><br>
  <textarea 
    id="description" 
    type="text" 
    name="cat[description]"><%=@cat.description%></textarea>
  <br>
    
  <input 
    type = "submit" 
    value = "<%= (action == :new) ? "Create Cat!" : "Edit Cat!"%>">
    
</form> 

<a href="<%= cats_url %>">Home</a>

app/views/cats/edit.html.erb
<h1>Edit a Cat!</h1>


<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>All The Cats!</h1>

<ol>
  <%@cats.each do |cat| %>
  <li> <a href = "<%= cat_url(cat) %>"> <%= cat.name%></a> </li>
<%end%>
</ol>

<a href="<%= new_cat_url %>">Add a New Cat!</a>
<a href="<%= new_cat_rental_request_url %>">Rent a Cat!</a>

app/views/cats/new.html.erb
<h1>Create a Cat!</h1>


<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1><%=@cat.name%></h1>
<table>
    <tr>
        <th>Attribute</th>
        <th>Value</th>
    </tr>

    <%[:age, :birth_date, :color, :sex].each do |attr|%>
        <tr>
        <td> <%=attr.to_s.capitalize%></td> 
        <td> <%= @cat.send(attr) %></td>
        </tr>
    <%end%>
</table>

<h1>Rental Requests</h1>
<table>
    <tr>    
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
    </tr>
    
    <% @cat.rental_requests.order('start_date').each do |cat_rental|%>
    <tr>

        <td> <%=cat_rental.start_date%> </td>
        <td> <%=cat_rental.end_date%> </td>
        
        <%if cat_rental.pending? %>
         
         <!--Approved cat rental button-->
            <td> <form action="<%=approve_cat_rental_request_url(cat_rental)%>" method="POST">
            <input type="submit" name="cat_rental_request[status]" value="APPROVED"> 
            </form> </td>
        
        <!--Denied cat rental button-->
            <td> <form action="<%=deny_cat_rental_request_url(cat_rental)%>" method="POST">
            <input type="submit" name="cat_rental_request[status]" value="DENIED"> 
            </form> </td>

        <%elsif cat_rental.status == "DENIED" %>
            <td>Denied</td>
        <%elsif cat_rental.status == "APPROVED" %>
            <td>Approved</td>
        <%end%>
    </tr>
    <%end%>
   
</table>



<a href="<%= cats_url %>">HOME</a>

<!-- 
Goal: To Add Buttons

1) On the Cat show page, make a button to approve or deny a cat request.
2) You may add two member routes to cat_rental_requests: approve and deny.

--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NintyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>